name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go                                              # added by myself

    - name: Check out code into the Go module directory   # added by myself
      uses: actions/checkout@v3                           # added by myself

    - name: Test
      run:  make test                                     # go test -v ./...
